#pragma once

#include <string>

namespace Games {
	// ROM-ONLY
	const std::string ALLEYWAY = "Alleyway (World).zip"; // broken joypad
	const std::string AMIDA = "Amida (Japan).zip";
	const std::string ASTEROIDS = "Asteroids (USA, Europe).zip";
	const std::string BATTLECITY = "BattleCity (Japan).zip";
	const std::string BOMB_JACK = "Bomb Jack (Europe).zip";
	const std::string BOUKEN = "Bouken! Puzzle Road (Japan).zip"; // "Daedalian Opus (USA).zip"
	const std::string BOXXLE = "Boxxle (USA, Europe) (Rev A).zip";
	const std::string BOXXLE_II = "Boxxle II (USA, Europe).zip";
	const std::string BRAIN_BENDER = "Brain Bender (Europe).zip";
	const std::string BUBBLE_GHOST = "Bubble Ghost (USA, Europe).zip";
	const std::string CASTELIAN = "Castelian (Europe).zip"; // "Kyoro-chan Land (Japan).zip"
	const std::string CATRAP = "Catrap (USA).zip";
	const std::string CENTIPEDE = "Centipede (USA, Europe).zip";
	const std::string CHIKI_CHIKI_TENGOKU = "Chiki Chiki Tengoku (Japan).zip";
	const std::string COOL_BALL = "Cool Ball (USA).zip";
	const std::string DAEDALIAN_OPUS = "Daedalian Opus (USA).zip"; // "Bouken! Puzzle Road (Japan).zip"
	const std::string CRYSTAL_QUEST = "Crystal Quest (USA).zip";
	const std::string DR_MARIO = "Dr. Mario (World) (Rev A).zip";
	const std::string DRAGON_SLAYER_I = "Dragon Slayer I (Japan).zip"; // broken map/offsets
	const std::string DROPZONE = "Dropzone (Europe).zip";
	const std::string FLAPPY_SPECIAL = "Flappy Special (Japan).zip";
	const std::string FLIPULL = "Flipull (USA).zip";
	const std::string HEIANKYO_ALIEN = "Heiankyo Alien (USA).zip";
	const std::string HONG_KONG = "Hong Kong (Japan).zip";
	const std::string HYPER_LODE_RUNNER = "Hyper Lode Runner (World) (Rev A).zip";
	const std::string ISHIDO_THE_WAY_OF_STONES = "Ishido - The Way of Stones (Japan).zip"; // level doesn't start
	const std::string KAKOMUNJA = "Kakomunja (Japan).zip";
	const std::string KLAX = "Klax (Japan).zip";
	const std::string KOI_WA_KAKEHIKI = "Koi wa Kakehiki (Japan).zip";
	const std::string KORO_DICE = "Koro Dice (Japan).zip";
	const std::string KWIRK_HES_A_MAZE_ING = "Kwirk - He's A-maze-ing! (USA, Europe).zip";
	const std::string KYORO_CHAN_LAND = "Kyoro-chan Land (Japan).zip"; // Castelian (Europe).zip
	const std::string LOOPZ = "Loopz (World).zip";
	const std::string MASTER_KARATEKA = "Master Karateka (Japan).zip";
	const std::string MIGRAIN = "Migrain (Japan).zip"; // "Brain Bender (Europe).zip"
	const std::string MINESWEEPER_SOUKAITEI = "Minesweeper - Soukaitei (Japan).zip";
	const std::string MISSILE_COMMAND = "Missile Command (USA, Europe).zip";
	const std::string MOGURA_DE_PON = "Mogura de Pon! (Japan).zip";
	const std::string MOTOCROSS_MANIACS = "Motocross Maniacs (Europe) (Rev A).zip"; // levels break after scrolling a bit
	const std::string NFL_FOOTBALL = "NFL Football (USA).zip";
	const std::string OTHELLO = "Othello (Europe).zip"; // "Game Start" broken
	const std::string PALAMEDES = "Palamedes (Europe).zip";
	const std::string PENGUIN_LAND = "Penguin Land (Japan).zip";
	const std::string PIPE_DREAM = "Pipe Dream (USA).zip"; // broken "current" tile
	const std::string PITMAN = "Pitman (Japan).zip"; //"Catrap (USA).zip"
	const std::string POP_UP = "Pop Up (Europe).zip"; //"Cool Ball (USA).zip"
	const std::string PUZZLE_BOY = "Puzzle Boy (Japan).zip"; //"Kwirk - He's A-maze-ing! (USA, Europe).zip"
	const std::string Q_BILLION = "Q Billion (USA).zip";
	const std::string SERPENT = "Serpent (USA).zip";
	const std::string SHANGHAI = "Shanghai (USA).zip";
	const std::string SOUKOBAN = "Soukoban (Japan).zip"; // "Boxxle (USA, Europe) (Rev A).zip"
	const std::string SOUKOBAN_2 = "Soukoban 2 (Japan).zip"; // "Boxxle II (USA, Europe).zip"
	const std::string SPACE_INVADERS = "Space Invaders (Japan).zip";
	const std::string SPOT = "Spot (USA).zip"; // freeze after logo
	const std::string TASMANIA_STORY = "Tasmania Story (USA).zip";
	const std::string TENNIS = "Tennis (World).zip";
	const std::string TESSERAE = "Tesserae (Europe) (En,Fr,De,Es,It).zip";
	const std::string TETRIS = "Tetris (World) (Rev A).zip";
	const std::string TRUMP_BOY = "Trump Boy (Japan).zip";
	const std::string VOLLEY_FIRE = "Volley Fire (Japan).zip";
	const std::string WORLD_BOWLING = "World Bowling (USA).zip";
	const std::string YOKUMAN = "Yakuman (Japan) (Rev A).zip";
	const std::string CPU_INSTR_01_SPECIAL = "gb-test-roms-master\\cpu_instrs\\individual\\01-special.gb";
	const std::string CPU_INSTR_02_INTERRUPTS = "gb-test-roms-master\\cpu_instrs\\individual\\02-interrupts.gb";
	const std::string CPU_INSTR_03_OP_SP_HL = "gb-test-roms-master\\cpu_instrs\\individual\\03-op sp,hl.gb";
	const std::string CPU_INSTR_04_OP_R_IMM = "gb-test-roms-master\\cpu_instrs\\individual\\04-op r,imm.gb";
	const std::string CPU_INSTR_05_OP_RP = "gb-test-roms-master\\cpu_instrs\\individual\\05-op rp.gb";
	const std::string CPU_INSTR_06_LD_R_R = "gb-test-roms-master\\cpu_instrs\\individual\\06-ld r,r.gb";
	const std::string CPU_INSTR_07_JR_JP_CALL_RET_RST = "gb-test-roms-master\\cpu_instrs\\individual\\07-jr,jp,call,ret,rst.gb";
	const std::string CPU_INSTR_08_MISC_INSTRS = "gb-test-roms-master\\cpu_instrs\\individual\\08-misc instrs.gb";
	const std::string CPU_INSTR_09_OP_R_R = "gb-test-roms-master\\cpu_instrs\\individual\\09-op r,r.gb";
	const std::string CPU_INSTR_10_BIT_OPS = "gb-test-roms-master\\cpu_instrs\\individual\\10-bit ops.gb";
	const std::string CPU_INSTR_11_OP_A_HL = "gb-test-roms-master\\cpu_instrs\\individual\\11-op a,(hl).gb";
	const std::string INSTR_TIMING = "gb-test-roms-master\\instr_timing\\instr_timing.gb";
	const std::string INTERRUPT_TIME = "gb-test-roms-master\\interrupt_time\\interrupt_time.gb";
	const std::string MEM_TIMING_01_READ_TIMING = "gb-test-roms-master\\mem_timing\\individual\\01-read_timing.gb";
	const std::string MEM_TIMING_02_WRITE_TIMING = "gb-test-roms-master\\mem_timing\\individual\\02-write_timing.gb";
	const std::string MEM_TIMING_03_MODIFY_TIMING = "gb-test-roms-master\\mem_timing\\individual\\03-modify_timing.gb";
	const std::string MEM_TIMING_2_01_READ_TIMING = "gb-test-roms-master\\mem_timing-2\\rom_singles\\01-read_timing.gb";
	const std::string MEM_TIMING_2_02_WRITE_TIMING = "gb-test-roms-master\\mem_timing-2\\rom_singles\\02-write_timing.gb";
	const std::string MEM_TIMING_2_03_MODIFY_TIMING = "gb-test-roms-master\\mem_timing-2\\rom_singles\\03-modify_timing.gb";
	const std::string OAM_BUG_1_LCD_SYNC = "gb-test-roms-master\\oam_bug\\rom_singles\\1-lcd_sync.gb";
	const std::string OAM_BUG_2_CAUSES = "gb-test-roms-master\\oam_bug\\rom_singles\\2-causes.gb";
	const std::string OAM_BUG_3_NON_CAUSES = "gb-test-roms-master\\oam_bug\\rom_singles\\3-non_causes.gb";
	const std::string OAM_BUG_4_SCANLINE_TIMING = "gb-test-roms-master\\oam_bug\\rom_singles\\4-scanline_timing.gb";
	const std::string OAM_BUG_5_TIMING_BUG = "gb-test-roms-master\\oam_bug\\rom_singles\\5-timing_bug.gb";
	const std::string OAM_BUG_6_TIMING_NO_BUG = "gb-test-roms-master\\oam_bug\\rom_singles\\6-timing_no_bug.gb";
	const std::string OAM_BUG_7_TIMING_EFFECT = "gb-test-roms-master\\oam_bug\\rom_singles\\7-timing_effect.gb";
	const std::string OAM_BUG_8_INSTR_EFFECT = "gb-test-roms-master\\oam_bug\\rom_singles\\8-instr_effect.gb";
	const std::string HALT_BUG = "gb-test-roms-master\\halt_bug.gb";
	const std::string GEKKIO_BITS_MEM_OAM = "gekkio\\bits\\mem_oam.gb";
	const std::string GEKKIO_BITS_REG_F = "gekkio\\bits\\reg_f.gb";
	const std::string GEKKIO_BITS_UNUSED_HWIO = "gekkio\\bits\\unused_hwio-GS.gb";
	const std::string GEKKIO_INSTR_DAA = "gekkio\\instr\\daa.zip";
	const std::string GEKKIO_INTERRUPTS_IE_PUSH = "gekkio\\interrupts\\ie_push.gb";
	const std::string GEKKIO_OAM_DMA_BASIC = "gekkio\\oam_dma\\basic.gb";
	const std::string GEKKIO_OAM_DMA_REG_READ = "gekkio\\oam_dma\\reg_read.gb";
	const std::string GEKKIO_OAM_DMA_SOURCES = "gekkio\\oam_dma\\sources-GS.gb";
	const std::string GEKKIO_ADD_SP_E_TIMING = "gekkio\\add_sp_e_timing.gb";
	const std::string GEKKIO_BOOT_DIV2_S = "gekkio\\boot_div2-S.gb";
	const std::string GEKKIO_CALL_CC_TIMING = "gekkio\\call_cc_timing.gb";
	const std::string GEKKIO_INTR_TIMING = "gekkio\\intr_timing.gb";
	const std::string HOMEBREW_EXEMAN = "homebrew\\exeman.gb";

	// ROM + MBC1
	const std::string ADDAMS_FAMILY_PUGSLEYS_SCAVENGER_HUNT = "Addams Family, The - Pugsley's Scavenger Hunt (USA, Europe).zip";
	const std::string ADDAMS_FAMILY = "Addams Family, The (USA).zip";
	const std::string ADVENTURE_ISLAND = "Adventure Island (USA, Europe).zip";
	const std::string ADVENTURE_ISLAND_II = "Adventure Island II - Aliens in Paradise (USA, Europe).zip";
	const std::string ADVENTURES_OF_LOLO = "Adventures of Lolo (Europe) (SGB Enhanced).zip";
	const std::string AMAZING_SPIDER_MAN = "Amazing Spider-Man, The (USA, Europe).zip";
	const std::string ALIEN_3 = "Alien 3 (USA, Europe).zip";
	const std::string SUPER_MARIO_LAND = "Super Mario Land (World) (Rev A).zip";

	// ROM + MBC1 + RAM + BATTERY
	const std::string DONKEY_KONG_LAND = "Donkey Kong Land (USA, Europe) (SGB Enhanced).zip";
	const std::string LEGEND_OF_ZELDA_LINKS_AWAKENING = "Legend of Zelda, The - Link's Awakening (USA, Europe).zip";
	const std::string MARIOS_PICROSS = "Mario's Picross (USA, Europe) (SGB Enhanced).zip";
	const std::string METROID_II_RETURN_OF_SAMUS = "Metroid II - Return of Samus (World).zip";
	const std::string SUPER_MARIO_LAND_2_6_GOLDEN_COINS = "Super Mario Land 2 - 6 Golden Coins (USA, Europe).zip"; // crashes emulator
	const std::string HARVEST_MOON = "Harvest Moon GB (USA) (SGB Enhanced).zip"; // doesn't boot

	// ROM + MBC2 
	const std::string ARETHA = "Aretha (Japan).zip";
	const std::string FINAL_FANTASY_ADVENTURE = "Final Fantasy Adventure (USA).zip";
	const std::string FINAL_FANTASY_LEGEND = "Final Fantasy Legend, The (USA).zip";
	const std::string KID_ICARUS = "Kid Icarus - Of Myths and Monsters (USA, Europe).zip";
	const std::string KIRBYS_PINBALL_LAND = "Kirby's Pinball Land (USA, Europe).zip"; // doesn't boot
	const std::string ULTRA_GOLD = "Ultra Golf (USA).zip";


	// ROM + MBC3
	const std::string POCKET_MONSTERS_PIKACHU = "Pocket Monsters - Pikachu (Japan) (SGB Enhanced).zip";
	const std::string POKEMON_BLUE = "Pokemon - Blue Version (USA, Europe) (SGB Enhanced).zip";
	const std::string KANDUME_MONSTERS = "Kandume Monsters (Japan) (SGB Enhanced).zip"; // doesn't boot
	const std::string MINI_YONKY_LETS_GO = "Mini Yonku GB Let's & Go!! - All-Star Battle Max (Japan) (SGB Enhanced).zip";
	const std::string WARIO_LAND_II = "Wario Land II (USA, Europe) (SGB Enhanced).zip";
	const std::string BOKUJOU_MONOGATARI = "Bokujou Monogatari GB (Japan) (SGB Enhanced).zip";


	// ROM + MBC5
	const std::string POKEMON_AMARILLA = "Pokemon - Edicion Amarilla - Edicion Especial Pikachu (Spain) (GBC,SGB Enhanced).zip";
	const std::string POKEMON_GELBE = "Pokemon - Gelbe Edition - Special Pikachu Edition (Germany) (GBC,SGB Enhanced).zip";

	const std::string SOUND_DEMO = "sound_demo.zip";
	const std::string GBSOUND = "gbsound.zip";
    const std::string SFXGENERATOR = "SFXGenerator.zip";
    const std::string DEATHRAY = "DeathrayFreeVersion2009-fixed.zip";
    const std::string DRUMTECH = "DrumTechFreeVersion2009-fixed.zip";
    const std::string MUSICTECH_1 = "MusicTechV1FreeVersion2009-fixed.zip";
    const std::string MUSICTECH_2 = "MusicTechV2FreeVersion2009-fixed.zip";
    
    const std::string FACEBALL_2000 = "Faceball 2000 (USA).zip";
    const std::string F1_RACE = "F-1 Race (World).zip";

    const std::string CASTLEVANIA = "Castlevania - The Adventure (Europe).zip";
    const std::string CASTLEVANIA_2 = "Castlevania II - Belmont's Revenge (USA, Europe).zip";
    const std::string CASTLEVANIA_LEGENDS = "Castlevania Legends (USA, Europe) (SGB Enhanced).zip";
    const std::string DONKEY_KONG_LAND_2 = "Donkey Kong Land 2 (USA, Europe) (SGB Enhanced).zip";
    const std::string DONKEY_KONG_LAND_3 = "Donkey Kong Land III (USA, Europe) (Rev A) (SGB Enhanced).zip";
    const std::string DUCKTALES = "DuckTales (Europe).zip";
    const std::string DUCKTALES_2 = "DuckTales 2 (Europe).zip";
    const std::string ALADDIN = "Aladdin (Europe) (SGB Enhanced).zip";
    const std::string ANIMANIACS = "Animaniacs (Europe) (SGB Enhanced).zip";
    const std::string BATMAN_RETURN_OF_THE_JOCKER = "Batman - Return of the Joker (USA, Europe).zip";
    const std::string BATTLETOADS = "Battletoads (USA, Europe).zip";
    const std::string BLASTER_MASTER_JR = "Blaster Master Jr. (Europe).zip";
    const std::string BOMBERMAN = "Bomberman GB (USA, Europe) (SGB Enhanced).zip";
    const std::string BUGS_BUNNY_CRAZY_CASTLE = "Bugs Bunny Crazy Castle, The (USA, Europe).zip";
    const std::string BUGS_BUNNY_CRAZY_CASTLE_2 = "Bugs Bunny Crazy Castle 2, The (USA).zip";
    const std::string CAPTAIN_AMERICA = "Captain America and the Avengers (USA).zip";
    const std::string CONTRA = "Contra - The Alien Wars (USA) (SGB Enhanced).zip";
    const std::string COOL_SPOT = "Cool Spot (Europe).zip";
    const std::string DAFFY_DUCK = "Daffy Duck (USA, Europe) (SGB Enhanced).zip";
    const std::string DARKWING_DUCK = "Darkwing Duck (Europe).zip";
    const std::string DIABLO = "Diablo (USA) (Proto).zip";
    const std::string EARTHWORM_JIM = "Earthworm Jim (Europe).zip";
    const std::string FELIX_THE_CAT = "Felix the Cat (USA, Europe).zip";
    const std::string FLASH = "Flash, The (USA, Europe).zip";
    const std::string GARFIELD = "Garfield Labyrinth (Europe).zip";
    const std::string GARGOYLES_QUEST = "Gargoyle's Quest (USA, Europe).zip";
    const std::string GAUNTLET = "Gauntlet II (USA, Europe).zip";

	// CGB

	const std::string CGB_ALADDIN = "cgb/Aladdin (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_ALONE_IN_THE_DARK = "cgb/Alone in the Dark - The New Nightmare (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_DUKE_NUKEM = "cgb/Duke Nukem (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_GEX_ENTER_THE_GECKO = "cgb/Gex - Enter the Gecko (USA, Europe) (GB Compatible).zip";
    const std::string CGB_GRAND_THEFT_AUTO = "cgb/Grand Theft Auto (Europe) (En,Fr,De,Es,It) (GB Compatible).zip";
    const std::string CGB_GRAND_THEFT_AUTO_2 = "cgb/Grand Theft Auto 2 (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_LEGEND_OF_ZELDA_LINKS_AWAKENING_DX = "cgb/Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev B) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_LEGEND_OF_ZELDA_ORACLE_OF_SEASONS = "cgb/Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_MARIO_TENNIS = "cgb/Mario Tennis (Europe).zip";
    const std::string CGB_POKEMON_CRYSTAL = "cgb/Pokemon - Crystal Version (USA, Europe) (Rev A).zip";
    const std::string CGB_RAYMAN_2 = "cgb/Rayman 2 - The Great Escape (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_SUPER_MARIO_BROS_DELUX = "cgb/Super Mario Bros. Deluxe (USA, Europe) (Rev B).zip";
    const std::string CGB_TETRIS_DX = "cgb/Tetris DX (World) (SGB Enhanced) (GB Compatible).zip";

    const std::string CGB_BATMAN_OF_THE_FUTURE = "cgb/Batman of the Future - Return of the Joker (Europe) (En,Fr,De).zip";
    const std::string CGB_BOMBERMAN_MAX = "cgb/Bomberman Max - Blue Champion (USA).zip";
    const std::string CGB_CANNON_FODDER = "cgb/Cannon Fodder (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_CONKERS = "cgb/Conker's Pocket Tales (USA, Europe) (En,Fr,De) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_CROC = "cgb/Croc (USA, Europe).zip";
    const std::string CGB_CROC_2 = "cgb/Croc 2 (USA, Europe).zip";
	const std::string CGB_CRYSTALIS = "cgb/Crystalis (USA).zip";
    const std::string CGB_DONKEY_KONG_COUNTRY = "cgb/Donkey Kong Country (USA, Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_EARTHWORM_JIM = "cgb/Earthworm Jim - Menace 2 the Galaxy (USA, Europe) (GB Compatible).zip";
    const std::string CGB_GEX_3 = "cgb/Gex 3 - Deep Cover Gecko (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_MEGAMAN_EXTREME_2 = "cgb/Mega Man Xtreme 2 (USA, Europe).zip";
    const std::string CGB_METAL_GEAR_SOLID = "cgb/Metal Gear Solid (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_MS_PAC_MAN = "cgb/Ms. Pac-Man - Special Color Edition (USA) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_POKEMON_PINBALL = "cgb/Pokemon Pinball (Europe) (En,Fr,De,Es,It) (Rumble Version) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_POKEMON_TRADING_CARD = "cgb/Pokemon Trading Card Game (Europe) (En,Es,It) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_PRINCE_OF_PERSIA = "cgb/Prince of Persia (USA, Europe) (En,Fr,De,Es,It) (GB Compatible).zip";
    const std::string CGB_RAYMAN = "cgb/Rayman (USA) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_RESIDENT_EVIL_GAIDEN = "cgb/Resident Evil Gaiden (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_R_TYPE_DX = "cgb/R-Type DX (USA, Europe) (GB Compatible).zip";
    const std::string CGB_SPIDER_MAN_2 = "cgb/Spider-Man 2 - The Sinister Six (USA, Europe).zip";
    const std::string CGB_STREET_FIGHTER_ALPHA = "cgb/Street Fighter Alpha - Warriors' Dreams (Europe).zip";
    const std::string CGB_TOMB_RAIDER_CURSE = "cgb/Tomb Raider - Curse of the Sword (USA, Europe).zip";
    const std::string CGB_TOMB_RAIDER = "cgb/Tomb Raider (USA, Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_TONY_HAWKS = "cgb/Tony Hawk's Pro Skater (USA, Europe).zip";
    const std::string CGB_TONY_HAWKS_2 = "cgb/Tony Hawk's Pro Skater 2 (USA, Europe).zip";
    const std::string CGB_TONY_HAWKS_3 = "cgb/Tony Hawk's Pro Skater 3 (USA, Europe).zip";
    const std::string CGB_V_RALLY = "cgb/V-Rally - Championship Edition (USA) (En,Fr,Es).zip";
    const std::string CGB_WARIO_LAND_2 = "cgb/Wario Land II (USA, Europe) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_WARIO_LAND_3 = "cgb/Wario Land 3 (World) (En,Ja).zip";
    
    const std::string CGB_3D_POCKET_POOL = "cgb/3D Pocket Pool (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_3D_ULTRA_PINBALL = "cgb/3-D Ultra Pinball - Thrillride (USA) (Rumble Version).zip";
    const std::string CGB_007_THE_WORLD_IS_NOT_ENOUGH = "cgb/007 - The World Is Not Enough (USA, Europe).zip";
    const std::string CGB_ALICE_IN_WONDERLAND = "cgb/Alice in Wonderland (Europe) (En,Fr,De,Es).zip";
    const std::string CGB_DONALD_DUCK_QUACK_ATTACK = "cgb/Donald Duck - Quack Attack (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_DRAGON_BALL_Z_GUERREROS = "cgb/Dragon Ball Z - Guerreros de Leyenda (Spain).zip";
    const std::string CGB_DRAGON_TALES_DRAGON_ADVENTURES = "cgb/Dragon Tales - Dragon Adventures (USA).zip";
    const std::string CGB_DRAGON_WARRIOR_I_II = "cgb/Dragon Warrior I & II (USA) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_DRAGON_WARRIOR_III = "cgb/Dragon Warrior III (USA).zip";
    const std::string CGB_DRAGON_WARRIOR_MONSTERS = "cgb/Dragon Warrior Monsters (USA, Europe) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_DRAGONS_LAIR = "cgb/Dragon's Lair (USA, Europe) (En,Ja,Fr,De,Es,Zh).zip";
    const std::string CGB_DRIVER = "cgb/Driver - You are the Wheelman (USA) (En,Fr,De,Es,It).zip";
    const std::string CGB_FROGGER = "cgb/Frogger (Europe) (En,Fr,De,Es,It,Nl) (GB Compatible).zip";
    const std::string CGB_FROGGER_2 = "cgb/Frogger 2 (USA).zip";
    const std::string CGB_GRANDIA = "cgb/Grandia - Parallel Trippers (Japan).zip";
    const std::string CGB_HARRY_POTTER_CHAMBER_OF_SECRETS = "cgb/Harry Potter and the Chamber of Secrets (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,Da).zip";
    const std::string CGB_HARRY_POTTER_SORCERERS_STONE = "cgb/Harry Potter and the Sorcerer's Stone (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi).zip";
    const std::string CGB_HARVEST_MOON = "cgb/Harvest Moon GB (Europe) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_HARVEST_MOON_2 = "cgb/Harvest Moon 2 GBC (Europe) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_HARVEST_MOON_3 = "cgb/Harvest Moon 3 GBC (USA).zip";
    const std::string CGB_JUNGLE_BOOK = "cgb/Jungle Book, The - Mowgli's Wild Adventure (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_LEGEND_OF_ZELDA_ORACLE_OF_AGES = "cgb/Legend of Zelda, The - Oracle of Ages (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_LEGO_ALPHA_TEAM = "cgb/LEGO Alpha Team (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da).zip";
    const std::string CGB_LEGO_ISLAND_2 = "cgb/LEGO Island 2 - The Brickster's Revenge (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da).zip";
    const std::string CGB_LEGO_RACERS = "cgb/LEGO Racers (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da).zip";
    const std::string CGB_LEGO_STUNT_RALLY = "cgb/LEGO Stunt Rally (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da).zip";
    const std::string CGB_LION_KING = "cgb/Lion King, The - Simba's Mighty Adventure (USA, Europe).zip";
    const std::string CGB_LITTLE_MERMAID = "cgb/Little Mermaid II, The - Pinball Frenzy (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_LOONEY_TUNES_COLLECTOR = "cgb/Looney Tunes Collector - Martian Revenge! (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_LOONEY_TUNES_RACING = "cgb/Looney Tunes Racing (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_LUCKY_LUKE_DESPERADO = "cgb/Lucky Luke - Desperado Train (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_LUCKY_LUKE = "cgb/Lucky Luke (Europe) (En,Fr,De,Es).zip";
    const std::string CGB_LUFIA = "cgb/Lufia - The Legend Returns (Europe) (En,De).zip";
    const std::string CGB_MAGICAL_TETRIS_CHALLENGE = "cgb/Magical Tetris Challenge (Europe) (En,Fr,De,Es,It,Nl,Sv).zip";
    const std::string CGB_MARIO_GOLF = "cgb/Mario Golf (Europe).zip";

    const std::string CGB_FIFA_2000 = "cgb/FIFA 2000 (USA, Europe) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_FLINTSTONES = "cgb/Flintstones, The - Burgertime in Bedrock (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_GODZILLA = "cgb/Godzilla - The Series (Europe) (En,Fr,De) (GB Compatible).zip";
    const std::string CGB_XMEN_MUTANT_ACADEMY = "cgb/X-Men - Mutant Academy (USA, Europe).zip";
    const std::string CGB_XMEN_MUTANT_WARS = "cgb/X-Men - Mutant Wars (USA, Europe).zip";
    const std::string CGB_XMEN_WOLVERINES_RAGE = "cgb/X-Men - Wolverine's Rage (Europe).zip";
    const std::string CGB_WORMS_ARMAGEDDON = "cgb/Worms Armageddon (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_WETRIX = "cgb/Wetrix GB (Europe) (En,Fr,De).zip";
    const std::string CGB_WACKY_RACES = "cgb/Wacky Races (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_TYRIAN_2000 = "cgb/Tyrian 2000 (USA) (Proto) (GB Compatible).zip";
    const std::string CGB_TUROK = "cgb/Turok - Rage Wars (USA, Europe) (En,Fr,De,Es).zip";
    const std::string CGB_TUROK_2 = "cgb/Turok 2 - Seeds of Evil (USA, Europe) (En,Fr,De,Es) (GB Compatible).zip";
    const std::string CGB_TUROK_3 = "cgb/Turok 3 - Shadow of Oblivion (USA, Europe) (En,Fr,De,Es).zip";
    const std::string CGB_TOY_STORY_2 = "cgb/Toy Story 2 (USA, Europe) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_RAINBOW_SIX = "cgb/Tom Clancy's Rainbow Six (USA, Europe) (En,Fr,De).zip";
    const std::string CGB_TITUS_THE_FOX = "cgb/Titus the Fox to Marrakech and Back (USA) (GB Compatible).zip";
    const std::string CGB_TINY_TOON_ADVENTURES_BUSTER = "cgb/Tiny Toon Adventures - Buster Saves the Day (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_TINY_TOON_ADVENTURES_DIZZY = "cgb/Tiny Toon Adventures - Dizzy's Candy Quest (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_TEST_DRIVE = "cgb/Test Drive 2001 (USA).zip";
    const std::string CGB_TARZAN = "cgb/Tarzan (USA, Europe).zip";
    const std::string CGB_SUPER_BREAKOUT = "cgb/Super Breakout! (Europe) (En,Fr,De,Es,It,Nl) (GB Compatible).zip";
    const std::string CGB_STAR_WARS_OBI_WAN = "cgb/Star Wars Episode I - Obi-Wan's Adventures (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_STAR_WARS_RACER = "cgb/Star Wars Episode I - Racer (USA, Europe) (Rumble Version).zip";
    const std::string CGB_SPONGEBOB = "cgb/SpongeBob SquarePants - Legend of the Lost Spatula (USA, Europe).zip";
    const std::string CGB_SPAWN = "cgb/Spawn (USA).zip";
    const std::string CGB_SIMPSONS = "cgb/Simpsons, The - Night of the Living Treehouse of Horror (USA, Europe).zip";
    const std::string CGB_SHANTAE = "cgb/Shantae (USA).zip";
    const std::string CGB_ROBOCOP = "cgb/RoboCop (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_PUZZLED = "cgb/Puzzled (Europe) (En,Fr,De).zip";

    const std::string CGB_POKEMON_ORO = "cgb/Pokemon - Edicion Oro (Spain) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_POKEMON_PLATA = "cgb/Pokemon - Edicion Plata (Spain) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_AUSTIN_POWERS_BEHAVE = "cgb/Austin Powers - Oh, Behave! (USA).zip";
    const std::string CGB_AUSTIN_POWERS_WELCOME = "cgb/Austin Powers - Welcome to my Underground Lair! (USA).zip";
    const std::string CGB_LOVE_HINA_POCKET = "cgb/Love Hina Pocket (Japan).zip";
    const std::string CGB_PERFECT_DARK = "cgb/Perfect Dark (USA, Europe) (En,Fr,De,Es,It) (Rumble Version).zip";
    const std::string CGB_STAR_OCEAN = "cgb/Star Ocean - Blue Sphere (Japan) (SGB Enhanced) (GB Compatible).zip";

    const std::string CGB_4X4_WORLD_TROPHY = "cgb/4x4 World Trophy (Europe) (En,Fr,De,Es,It) (GB Compatible).zip";
    const std::string CGB_102_DALMATAS = "cgb/102 Dalmatas - Cachorros Al Rescate (Spain).zip";
    const std::string CGB_ANIMORPHS = "cgb/Animorphs (Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_ANTZ = "cgb/Antz (Europe) (En,Fr,De,Es,It,Nl) (GB Compatible).zip";
    const std::string CGB_ARMY_MEN = "cgb/Army Men (USA, Europe) (En,Fr,De).zip";
    const std::string CGB_ARMY_MEN_2 = "cgb/Army Men 2 (USA, Europe) (En,Fr,De).zip";
    const std::string CGB_ASTERIX_SEARCH_FOR_DOGMATIX = "cgb/Asterix - Search for Dogmatix (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_ASTERIX_OBELYX = "cgb/Asterix & Obelix (Europe) (En,Fr,De,Es).zip";
    const std::string CGB_BLADE = "cgb/Blade (USA, Europe).zip";
    const std::string CGB_BOMBERMAN_QUEST = "cgb/Bomberman Quest (Europe) (En,Fr,De) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_BUFFY = "cgb/Buffy the Vampire Slayer (USA, Europe).zip";
    const std::string CGB_BUGS_BUNNY_CRAZY_CASTLE_3 = "cgb/Bugs Bunny - Crazy Castle 3 (USA, Europe) (GB Compatible).zip";
    const std::string CGB_BUGS_BUNNY_LOLA_BUNNY = "cgb/Bugs Bunny & Lola Bunny - Operation Carrots (Europe) (En,Fr,De,Es,It,Nl) (GB Compatible).zip";
    const std::string CGB_BUGS_BUNNY_CRAZY_CASTLE_4 = "cgb/Bugs Bunny in Crazy Castle 4 (Europe).zip";
    const std::string CGB_BUGS_LIFE = "cgb/Bug's Life, A (Europe) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_BUST_A_MOVE_4 = "cgb/Bust-A-Move 4 (USA, Europe) (GB Compatible).zip";
    const std::string CGB_CATWOMAN = "cgb/Catwoman (Europe).zip";
    const std::string CGB_COLIN_MCRAE_RALLY = "cgb/Colin McRae Rally (Europe).zip";
    const std::string CGB_GHOSTS_N_GOBLINS = "cgb/Ghosts'n Goblins (USA, Europe) (GB Compatible).zip";
    const std::string CGB_HERCULES = "cgb/Hercules - The Legendary Journeys (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_INSPECTOR_GADGET = "cgb/Inspector Gadget - Operation Madkactus (Europe) (En,Fr,De,Es,It,Nl).zip";
    const std::string CGB_LOGICAL = "cgb/Logical (Europe).zip";
    const std::string CGB_MAGICAL_DROP = "cgb/Magical Drop (Europe) (En,Fr,De).zip";
    const std::string CGB_MEGAMAN_XTREME = "cgb/Mega Man Xtreme (USA, Europe) (GB Compatible).zip";
    const std::string CGB_MEN_IN_BLACK = "cgb/Men in Black - The Series (USA, Europe) (SGB Enhanced) (GB Compatible).zip";
    const std::string CGB_MEN_IN_BLACK_2 = "cgb/Men in Black 2 - The Series (Europe) (En,Fr,De).zip";
    const std::string CGB_MICKEYS_RACING = "cgb/Mickey's Racing Adventure (USA, Europe) (En,Fr,De,Es,It).zip";
    const std::string CGB_KIRBY = "cgb/Kirby - Tilt 'n' Tumble (USA).zip";
    const std::string CGB_31_IN_1 = "cgb/31-in-1 Mighty Mix (Australia) (31B-001, Sachen) (Unl).zip";
}
